# Project-wide Gradle settings.
# Android Gradle plugin requires at least 2GB of memory.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Use AndroidX
android.useAndroidX=true

# Enable parallel and configuration caching for speed
org.gradle.parallel=true
org.gradle.caching=true
